import type { IndustryCrudConfig } from '@/lib/admin-industry-api';

export const clubCrudConfig: IndustryCrudConfig = {
  table: 'sup_clubs',
  idField: 'club_id',
  entityLabel: '俱乐部',
  requiredFields: ['slug', 'name'],
  textFields: [
    'slug',
    'name',
    'logo',
    'cover_image',
    'province',
    'city',
    'district',
    'address',
    'water_area_name',
    'water_type',
    'intro',
    'opening_hours',
    'contact_method',
    'claim_status',
    'verification_status',
    'source_type',
    'source_note',
    'status',
  ],
  jsonFields: ['images', 'services', 'safety_facilities', 'training_environment'],
  numberFields: ['lat', 'lng', 'owner_user_id', 'sort_order'],
  searchFields: ['sup_clubs.name', 'sup_clubs.city', 'sup_clubs.water_area_name', 'sup_clubs.address'],
  defaultOrder: "CASE status WHEN 'published' THEN 0 ELSE 1 END, sort_order ASC, club_id DESC",
};

export const professionalCrudConfig: IndustryCrudConfig = {
  table: 'sup_professionals',
  idField: 'professional_id',
  entityLabel: '专业人员',
  requiredFields: ['name'],
  textFields: [
    'name',
    'avatar',
    'gender',
    'province',
    'city',
    'primary_role',
    'bio',
    'intro_short',
    'wechat_contact',
    'phone_masked',
    'claim_status',
    'verification_status',
    'source_type',
    'source_note',
    'status',
  ],
  jsonFields: ['roles', 'specialties', 'service_items', 'teaching_level', 'teaching_environment'],
  numberFields: ['user_id', 'athlete_id', 'club_id', 'sort_order'],
  booleanFields: ['contact_visible'],
  searchFields: ['sup_professionals.name', 'sup_professionals.city', 'sup_professionals.bio', 'sup_professionals.intro_short'],
  filterFields: ['primary_role'],
  defaultOrder: "CASE status WHEN 'published' THEN 0 ELSE 1 END, sort_order ASC, professional_id DESC",
};

export const certificateCrudConfig: IndustryCrudConfig = {
  table: 'sup_professional_certificates',
  idField: 'certificate_id',
  entityLabel: '证书资料',
  requiredFields: ['professional_id', 'certificate_name'],
  textFields: [
    'certificate_name',
    'certificate_type',
    'certificate_level',
    'issuer',
    'certificate_no_masked',
    'certificate_image_url',
    'source_type',
    'verification_status',
    'remark',
    'status',
  ],
  numberFields: ['professional_id'],
  dateFields: ['issue_date', 'expiry_date'],
  searchFields: ['sup_professional_certificates.certificate_name', 'sup_professional_certificates.issuer', 'sup_professional_certificates.certificate_type'],
  defaultOrder: "CASE status WHEN 'published' THEN 0 ELSE 1 END, certificate_id DESC",
};

export const clubMemberCrudConfig: IndustryCrudConfig = {
  table: 'sup_club_members',
  idField: 'member_id',
  entityLabel: '俱乐部成员',
  requiredFields: ['club_id'],
  textFields: ['role', 'team_label', 'join_status', 'status'],
  numberFields: ['club_id', 'professional_id', 'athlete_id', 'user_id'],
  booleanFields: ['is_public'],
  searchFields: ['sup_club_members.role', 'sup_club_members.team_label'],
  defaultOrder: "CASE status WHEN 'published' THEN 0 ELSE 1 END, member_id DESC",
};
