INSERT INTO sup_events (
  name, name_en, slug, event_type, location, province, city, venue,
  start_date, end_date, registration_deadline, organizer, description, requirements,
  website, registration_url, contact_info, images, schedule, disciplines,
  price_range, max_participants, status, event_status
)
VALUES
(
  '2025年中国桨板超级联赛（三门峡站）',
  '2025 China SUP Super League (Sanmenxia Stop)',
  'china-sup-super-league-sanmenxia-2025',
  'race',
  '河南省三门峡市天鹅湖国家城市湿地公园陕州区水上运动中心水域',
  '河南',
  '三门峡',
  '天鹅湖国家城市湿地公园陕州区水上运动中心',
  '2025-05-17',
  '2025-05-17',
  NULL,
  '国家体育总局水上运动管理中心、三门峡市人民政府',
  '2025赛季首站中国桨板超级联赛，依托黄河生态资源打造国家级水上运动品牌赛事。官方报道明确提及其为五星级认证赛事，是全年国内高权重积分节点之一。',
  '参赛组别、报名资格与器材要求以当年官方竞赛规程、补充通知和报名须知为准。',
  'https://www.sport.gov.cn/sszx/n5206/c28729626/content.html',
  NULL,
  NULL,
  NULL,
  NULL,
  JSON_ARRAY('200米竞速', '长距离赛', '龙板赛', '公开组', '大师组', '卡胡纳组', '高校组', '青少年组'),
  NULL,
  NULL,
  'published',
  'completed'
),
(
  '2025年桨板亚洲杯暨中国桨板嘉年华',
  '2025 SUP Asia Cup & China SUP Carnival',
  'sup-asia-cup-qingtian-2025',
  'festival',
  '浙江省丽水市青田县',
  '浙江',
  '青田',
  '青田赛事水域',
  '2025-07-11',
  '2025-07-13',
  NULL,
  '国家体育总局水上运动管理中心、相关亚洲赛事组织及地方政府',
  '2025年桨板亚洲杯落地浙江青田，是国内少见的亚洲级高规格桨板赛事节点，同时联动中国桨板嘉年华。按照国内积分等级矩阵口径，可视作5星级国际/亚洲高层级窗口。',
  '国际组别、国内组别和现场活动安排以当年赛事公告、竞赛规程和报名通知为准。',
  'https://www.sport.gov.cn/n20001280/n20067662/n20067613/c28889639/content.html',
  NULL,
  NULL,
  NULL,
  NULL,
  JSON_ARRAY('亚洲杯', '公开组', '精英组', '竞速赛', '长距离赛', '嘉年华'),
  NULL,
  NULL,
  'published',
  'completed'
),
(
  '2025年中国桨板精英赛石嘴山站',
  '2025 China SUP Elite Series (Shizuishan)',
  'china-sup-elite-series-shizuishan-2025',
  'race',
  '宁夏回族自治区石嘴山市星海湖景区',
  '宁夏',
  '石嘴山',
  '星海湖景区',
  '2025-07-19',
  '2025-07-20',
  NULL,
  '国家体育总局水上运动管理中心、石嘴山市人民政府',
  '中国桨板精英赛是国家体育总局水上运动管理中心创立的赛事品牌，也是唯一设置精英组的国家级桨板赛。石嘴山站是2025年度高水平积分争夺的重要一站，精英组报名面向年度积分排名前列选手开放。',
  '精英组资格、公开组报名办法、器材规范和竞赛分组以当年官方补充通知和报名要求为准。',
  'https://www.sport.org.cn/shouye/xwzx/2025/0720/660887.html',
  NULL,
  NULL,
  NULL,
  NULL,
  JSON_ARRAY('精英组', '公开组', '大师组', '卡胡纳组', '青少年组', '200米竞速', '长距离技巧赛', '龙板赛'),
  NULL,
  NULL,
  'published',
  'completed'
),
(
  '2025全国桨板冠军赛（海口站）暨2025年全国桨板青少年U系列赛（海口站）',
  '2025 National SUP Championship (Haikou) & Youth U Series',
  'national-sup-championship-haikou-2025',
  'race',
  '海南省海口市自在湾',
  '海南',
  '海口',
  '自在湾',
  '2025-08-29',
  '2025-08-31',
  NULL,
  '国家体育总局水上运动管理中心、海南省旅游和文化广电体育厅',
  '海口站是2025年全国桨板冠军赛年度分站之一，并与全国桨板青少年U系列赛同步举行。赛事覆盖精英组、公开组、大师组、卡胡纳组及青少年组，是全年国家级核心赛事之一。',
  '各组别报名资格、海上赛道安全要求和比赛器材规范以赛事官方规程及补充通知为准。',
  'https://m.tech.china.com/digi/articles/20250901/202509011723804.html',
  NULL,
  NULL,
  NULL,
  NULL,
  JSON_ARRAY('精英组', '公开组', '大师组', '卡胡纳组', '青少年组', '200米竞速', '1000米技术赛', '3000米-6000米长距离赛', '龙板赛'),
  NULL,
  NULL,
  'published',
  'completed'
),
(
  '“奔跑吧·邵阳”2025年中国桨板超级联赛暨第四届天子湖桨板公开赛',
  '2025 China SUP Super League & 4th Tianzihu SUP Open',
  'china-sup-super-league-shaoyang-2025',
  'race',
  '湖南省邵阳县天子湖国家湿地公园',
  '湖南',
  '邵阳',
  '天子湖国家湿地公园',
  '2025-08-30',
  '2025-08-31',
  NULL,
  '国家体育总局水上运动管理中心、湖南省体育局、邵阳市人民政府',
  '邵阳站是2025年中国桨板超级联赛的重要一站，设公开组、大师组、卡胡纳组、高校组及青少年U系列等多组别赛事，并进一步强化了赛道规范和全民参与度。按赛事品牌层级可归入全年高等级导览序列。',
  '个人赛、团体赛及青少年组别的报名与安全要求以当年官方竞赛规程为准。',
  'https://www.sport.gov.cn/n20001280/n20067662/n20067613/c29024639/content.html',
  NULL,
  NULL,
  NULL,
  NULL,
  JSON_ARRAY('公开组', '大师组', '卡胡纳组', '高校组', '青少年U系列', '200米竞速', '3000米长距离', '10000米耐力赛', '混合四人竞速', '家庭三人竞速', '混合双人竞速'),
  NULL,
  NULL,
  'published',
  'completed'
),
(
  '2025年中国桨板公开赛（平顶山站）',
  '2025 China SUP Open (Pingdingshan)',
  'china-sup-open-pingdingshan-2025',
  'race',
  '河南省平顶山市白龟湖国家城市湿地公园',
  '河南',
  '平顶山',
  '白龟湖国家城市湿地公园',
  '2025-10-18',
  '2025-10-19',
  NULL,
  '国家体育总局水上运动管理中心、平顶山市人民政府',
  '中国桨板公开赛（平顶山站）是2025年国家级高规格公开赛节点之一，依托白龟湖水域举办。赛事兼具竞技水平与城市展示属性，可纳入全年4星级导览序列。',
  '竞赛项目、分组、报名和器材要求以官方竞赛规程与补充通知为准。',
  'https://www.pds.gov.cn/contents/4/175297.html',
  NULL,
  NULL,
  NULL,
  NULL,
  JSON_ARRAY('竞速赛', '公开组', '大师组', '青少年组', '长距离赛'),
  NULL,
  NULL,
  'published',
  'completed'
),
(
  '2025年中国百城桨板公开赛总决赛',
  '2025 China Hundred Cities SUP Open Finals',
  'china-city-sup-open-finals-keqiao-2025',
  'race',
  '浙江省绍兴市柯桥区瓜渚湖南岸公园',
  '浙江',
  '绍兴',
  '瓜渚湖南岸公园',
  '2025-10-25',
  '2025-10-25',
  NULL,
  '国家体育总局水上运动管理中心',
  '2025年中国百城桨板公开赛总决赛在绍兴柯桥举行，吸引来自全国28个省、市、自治区的近400名选手参赛。作为百城赛体系的总决赛，赛事在全国推广和大众竞技层面具有明显的高规格收官属性。',
  '总决赛报名资格、组别设置和成绩认定规则以赛事官方公告和补充规程为准。',
  'https://www.sport.gov.cn/sszx/n5206/c29150553/content.html',
  NULL,
  NULL,
  NULL,
  NULL,
  JSON_ARRAY('6000米长距离赛', '200米冲刺赛', '500米技术赛', '四人团队龙板赛', '混合双人赛'),
  NULL,
  NULL,
  'published',
  'completed'
),
(
  '2025全国桨板冠军赛总决赛暨全国桨板U系列赛（常熟站）',
  '2025 National SUP Championship Finals & U Series (Changshu)',
  'national-sup-championship-finals-changshu-2025',
  'race',
  '江苏省常熟市古城河',
  '江苏',
  '常熟',
  '古城河',
  '2025-11-08',
  '2025-11-08',
  NULL,
  '国家体育总局水上运动管理中心、常熟市人民政府',
  '常熟站是2025年全国桨板冠军赛总决赛暨全国桨板U系列赛收官站，被地方官方称为国内最高规格的桨板赛事。其在全年积分和竞技展示上的权重，适合放入4.5星级导览主线。',
  '总决赛参赛资格、青少年组报名和赛道安排以当年赛事规程、技术手册及官方通知为准。',
  'https://www.suzhou.gov.cn/szsrmzf/wtly/202511/1e371d4eb96d45a0bb19b6f8c6adf681.shtml',
  NULL,
  NULL,
  NULL,
  NULL,
  JSON_ARRAY('总决赛', '青少年U系列', '竞速赛', '长距离赛', '技术赛'),
  NULL,
  NULL,
  'published',
  'completed'
)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  name_en = VALUES(name_en),
  event_type = VALUES(event_type),
  location = VALUES(location),
  province = VALUES(province),
  city = VALUES(city),
  venue = VALUES(venue),
  start_date = VALUES(start_date),
  end_date = VALUES(end_date),
  registration_deadline = VALUES(registration_deadline),
  organizer = VALUES(organizer),
  description = VALUES(description),
  requirements = VALUES(requirements),
  website = VALUES(website),
  registration_url = VALUES(registration_url),
  contact_info = VALUES(contact_info),
  images = VALUES(images),
  schedule = VALUES(schedule),
  disciplines = VALUES(disciplines),
  price_range = VALUES(price_range),
  max_participants = VALUES(max_participants),
  status = VALUES(status),
  event_status = VALUES(event_status);
