-- migrate-learn.sql: SUP 学习模块 - 知识文章 + 题库

CREATE TABLE IF NOT EXISTS sup_learn_articles (
  article_id  INT AUTO_INCREMENT PRIMARY KEY,
  title       VARCHAR(200) NOT NULL,
  slug        VARCHAR(200) NOT NULL UNIQUE,
  category    VARCHAR(50)  NOT NULL,
  summary     TEXT,
  content     LONGTEXT,
  difficulty  ENUM('beginner','intermediate','advanced') NOT NULL DEFAULT 'beginner',
  sort_order  INT NOT NULL DEFAULT 0,
  status      ENUM('draft','published') NOT NULL DEFAULT 'draft',
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sup_quiz_questions (
  question_id  INT AUTO_INCREMENT PRIMARY KEY,
  question     TEXT NOT NULL,
  type         ENUM('single','multiple','truefalse') NOT NULL DEFAULT 'single',
  options      JSON,
  correct      JSON NOT NULL COMMENT '单选/判断为数字索引，多选为数组',
  explanation  TEXT,
  category     VARCHAR(50) NOT NULL,
  difficulty   ENUM('beginner','intermediate','advanced') NOT NULL DEFAULT 'beginner',
  status       ENUM('draft','published') NOT NULL DEFAULT 'published',
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ══ 题库初始数据 ══════════════════════════════════════════════

INSERT INTO sup_quiz_questions (question, type, options, correct, explanation, category, difficulty) VALUES

-- ── 装备知识（equipment） ──────────────────────────────────────
('SUP 是什么的缩写？',
 'single',
 '["Stand Up Paddleboard","Speed Under Paddle","Surf Under Power","Stand Under Pier"]',
 '0',
 'SUP 全称 Stand Up Paddleboard，即站立式桨板，是一种站在板上用桨划水的水上运动。',
 'equipment', 'beginner'),

('充气桨板建议充气到多少 PSI 才能达到最佳刚性？',
 'single',
 '["5-8 PSI","12-15 PSI","20-25 PSI","30 PSI 以上"]',
 '1',
 '大多数充气桨板推荐充气压力为 12-15 PSI，部分竞速充气板可达 18 PSI。气压过低板面会弯曲下沉，影响滑行效率。',
 'equipment', 'beginner'),

('Drop-Stitch（拉丝布）技术的作用是什么？',
 'single',
 '["增加防水性能","让充气板在高气压下保持平整刚性","减轻板的重量","提升板面抓水力"]',
 '1',
 'Drop-Stitch 是连接充气板上下两层 PVC 的无数细线，充气后这些线拉紧，使板面保持平整而不会气球状鼓起，从而获得接近硬板的刚性。',
 'equipment', 'beginner'),

('以下哪种板型最适合初学者？',
 'single',
 '["14尺×20寸竞速板","10尺6寸×32寸全能充气板","9尺×16寸冲浪板","12尺6寸×27寸竞速充气板"]',
 '1',
 '宽体全能板（10\'6" × 32"）稳定性最高，初学者容易保持平衡。竞速板太窄，冲浪板体积太小，都不适合入门。',
 'equipment', 'beginner'),

('硬板（实心板）相比充气板的主要优势是什么？',
 'multiple',
 '["更轻、刚性更好","便于携带和储存","滑行效率更高","维修成本更低"]',
 '[0, 2]',
 '硬板通常比同尺寸充气板更轻（尤其碳纤维板），刚性更好，滑行效率（速度）更高。充气板的优势则是便携和储存方便。',
 'equipment', 'intermediate'),

('ICF 代表哪个国际体育组织？',
 'single',
 '["国际冲浪协会","国际皮划艇联合会","国际帆板协会","国际水上运动联合会"]',
 '1',
 'ICF 是 International Canoe Federation（国际皮划艇联合会）的缩写，是 SUP 竞速项目的最高国际管理机构，2012年将桨板纳入管辖范围。',
 'equipment', 'intermediate'),

('碳纤维（Carbon Fiber）桨板的主要特点是什么？',
 'multiple',
 '["重量轻","强度高","价格低廉","抗UV能力极强"]',
 '[0, 1]',
 '碳纤维具有密度低（轻量）和拉伸强度极高的特点，是顶级赛板的首选材料。价格通常较贵，且需要避免碰撞以防分层。',
 'equipment', 'advanced'),

('判断：鳍（Fin）越大，板的直线追踪性越好。',
 'truefalse',
 '["正确","错误"]',
 '0',
 '基本正确。更大的鳍提供更多侧向阻力，减少偏航，提升直线追踪性，但也会增加水阻、降低速度灵活性。竞速板通常使用长而窄的竞速鳍。',
 'equipment', 'intermediate'),

('以下哪些属于 SUP 板的常见材质？',
 'multiple',
 '["EPS泡芯+玻璃纤维","碳纤维+真空层压","充气PVC Drop-Stitch","木质单板"]',
 '[0, 1, 2]',
 '主流材质：EPS泡芯+玻纤（入门/中端硬板）、碳纤维（竞速高端硬板）、充气PVC（全能/入门充气板）。木质桨板较为罕见，主要是工艺板或特定品牌产品。',
 'equipment', 'intermediate'),

('一块标准全能充气桨板的典型尺寸是多少？',
 'single',
 '["8\'0\" × 28\" × 4\"","10\'6\" × 32\" × 6\"","14\'0\" × 22\" × 6\"","12\'6\" × 27\" × 6\""]',
 '1',
 '10\'6"（320cm）× 32"（81cm）× 6"（15cm）是全能充气板最常见的规格，体积大、稳定性好，适合大多数成人初学者。',
 'equipment', 'beginner'),

-- ── 技术动作（technique） ──────────────────────────────────────
('标准划桨姿势中，握桨时上方手应握在哪里？',
 'single',
 '["握在桨叶上方约10cm处","握在T形桨柄顶端","握在桨杆中间","握在距桨叶1/3处"]',
 '1',
 '标准握法：上方手握住T形桨柄顶端（T-grip），下方手握桨杆，间距约肩宽。这样能最大化传递力量。',
 'technique', 'beginner'),

('向右转弯时，应该怎么划桨？',
 'single',
 '["左侧向后划（后扫桨）","右侧向前快划","两侧同时用力","停止划桨靠重心偏移"]',
 '0',
 '后扫桨（Sweep Stroke）：在板的左侧从前到后大弧度划水，产生向右的旋转力矩，使板头向右转。',
 'technique', 'beginner'),

('桨叶入水时，正确的角度应该是？',
 'single',
 '["桨叶完全垂直于水面","桨叶向前倾斜约10-15度","桨叶向后倾斜","平行于水面"]',
 '1',
 '桨叶入水时应略向前倾（约10-15度），确保抓水充分，减少向上的分力，提升推进效率。',
 'technique', 'intermediate'),

('落水后，正确的上板方式是？',
 'single',
 '["从板尾爬上去","从板中央（舵眼附近）侧面上板","直接从板头跳上去","先把桨放到板上再上板"]',
 '1',
 '应从板中央侧面上板，重心位于板的重心点附近，避免板头或板尾翘起。先把桨横放在板上，双手撑板，膝盖先上，再站起。',
 'technique', 'beginner'),

('判断：划桨时手臂应该伸直，主要用手臂力量推进。',
 'truefalse',
 '["正确","错误"]',
 '1',
 '错误。正确的划桨应充分利用核心肌肉（腰腹）和腿部，手臂只是传导力量的"杠杆"。过度依赖手臂会快速疲劳且效率低。',
 'technique', 'beginner'),

('长距离竞速比赛中，"Drafting"（跟风）是指什么？',
 'single',
 '["顺风划行","跟在前面运动员的尾流中划，减少水阻","使用特殊划桨技术","预判风向提前调整路线"]',
 '1',
 'Drafting 是竞速策略：紧随前方运动员，利用其破开的水流减少自身水阻，节省体力，在关键时刻超越。合法的竞技技术，但需要保持安全距离避免碰撞犯规。',
 'technique', 'advanced'),

('平水竞速中，提高效率的关键技术要点包括哪些？',
 'multiple',
 '["入水点靠近板头越远越好","划桨频率越快越好","充分利用核心肌肉转体","出水点在脚踝处即可出水"]',
 '[0, 2, 3]',
 '关键点：①入水尽量靠前（延长有效划程）；②充分转体调动核心肌群；③在脚踝处即出水（过晚出水会产生向上拉力）。频率过快反而降低每划推进效率，要找到最优节奏。',
 'technique', 'advanced'),

-- ── 竞赛规则（race） ──────────────────────────────────────────
('全国桨板冠军赛"精英组"的主要特点是？',
 'single',
 '["任何人均可报名参加","仅限职业注册运动员，成绩计入国家积分排名","仅限 18 岁以上运动员","须完成 3 场资格赛才能参加"]',
 '1',
 '全国冠军赛精英组是职业运动员角逐舞台，成绩纳入国家积分体系，是晋升国家队候补的重要通道。',
 'race', 'intermediate'),

('ICF 桨板世锦赛的主要竞赛距离包括哪些？',
 'multiple',
 '["200米冲刺赛","500米技术赛","1000米绕标赛","长距离赛（12公里以上）"]',
 '[0, 1, 3]',
 'ICF 世锦赛核心项目：200米冲刺（爆发力）、500米技术赛（速度+技术）、长距离赛（12km+，耐力）。',
 'race', 'intermediate'),

('"U18" 分组中的 "U" 代表什么？',
 'single',
 '["Universal（通用）","Under（xx岁以下）","Ultra（超级）","United（联合）"]',
 '1',
 'U 代表英文 Under（以下），U18 即 18岁以下青少年组。国际通用惯例：U9、U12、U15、U18 各组别独立计分，不与成人组竞争。',
 'race', 'beginner'),

('判断：在 CPL 联赛（中国桨板俱乐部联赛）中，卡胡纳组（Kahuna）是专为大体型运动员设立的组别。',
 'truefalse',
 '["正确","错误"]',
 '0',
 '正确。卡胡纳（Kahuna）组专为体重较重（通常 85kg 以上）的运动员设立，使用更宽更稳定的板型，确保公平竞争。',
 'race', 'intermediate'),

('竞速赛中，运动员绕标时犯规的常见情形是？',
 'multiple',
 '["从错误方向绕标（切标）","桨板碰触浮标","超越浮标边界","落水后未上板直接游泳继续比赛"]',
 '[0, 2, 3]',
 '常见犯规：切标（走近路绕标）、超越边界浮标、落水后游泳推进（必须上板或在板旁）。桨板轻微碰标通常不犯规，视规则细则而定。',
 'race', 'advanced'),

('APP World Tour 和 ICF 世锦赛的主要区别是？',
 'single',
 '["APP 只限美国选手","APP 是职业商业巡回赛，奖金丰厚；ICF 是官方锦标赛，代表国家荣誉","APP 只有充气板组别","两者完全相同"]',
 '1',
 'APP World Tour 是商业化职业巡回赛，有丰厚奖金，代表个人实力；ICF 世锦赛代表国家出赛，是最权威的官方荣誉。两者共同构成国际顶级 SUP 舞台。',
 'race', 'intermediate'),

-- ── 安全知识（safety） ──────────────────────────────────────────
('在开放水域（如海洋、大型湖泊）划桨板时，下列哪项安全装备是必须的？',
 'single',
 '["专业比赛板","踝绳（Leash）","防晒霜","碳纤维桨"]',
 '1',
 '踝绳（Leash）将运动员与桨板连接，落水后板不会漂走。在大浪或开放水域，失去板的后果极为严重，踝绳是最重要的安全装备。',
 'safety', 'beginner'),

('以下哪种天气/水况条件最危险，应避免下水？',
 'multiple',
 '["强侧风（离岸风）","轻微顺风","雷暴天气","水温低于15°C无防寒装备"]',
 '[0, 2, 3]',
 '强侧风（尤其离岸风）会把你吹离岸边无法返回；雷暴是极度危险的致命风险（桨是导体）；低水温下落水可能迅速失温。顺风通常是安全且有利的条件。',
 'safety', 'beginner'),

('PFD 是什么，在 SUP 运动中起什么作用？',
 'single',
 '["Personal Float Device，个人漂浮辅助装置（救生衣）","Paddle Float Device，桨板浮力设备","Personal Fin Design，个人鳍型设计","Performance Float Data，性能浮力数据"]',
 '0',
 'PFD（Personal Flotation Device）即救生衣，在 SUP 运动中用于防止溺水。在许多国家和地区，未成年人和特定水域划桨板时佩戴 PFD 是法律要求。',
 'safety', 'beginner'),

('判断：在内河（河流）中划桨板时，通常应顺水流方向佩戴踝绳。',
 'truefalse',
 '["正确","错误"]',
 '1',
 '错误。在急流/河流中，踝绳可能造成危险——落水后踝绳可能缠绕水下障碍物导致被拖拽。急流中的专业说法是：不建议或不使用踝绳，改用腰部安全绳（hip leash）。',
 'safety', 'advanced'),

('当你在水上发现有人溺水时，第一步应该做什么？',
 'single',
 '["立即跳水救人","大声呼救并拨打急救电话，同时评估情况","把桨板借给溺水者","继续划行去寻找专业救援人员"]',
 '1',
 '黄金原则：先确保自身安全，立即呼救拨打急救电话，评估能否安全施救（将桨板推给溺水者是有效辅助方式）。贸然跳水可能导致两人都陷入危险。',
 'safety', 'beginner'),

('离岸风（Offshore Wind）为什么对 SUP 运动者特别危险？',
 'single',
 '["风速太快容易摔倒","风向从岸边吹向外海，会把运动员越吹越远，难以返岸","会让水面波浪变大","会让板变得更难控制"]',
 '1',
 '离岸风方向是从陆地吹向海洋，顺风出发轻松，但返回时需要顶风划行，越来越困难。轻风离岸时可能已漂出很远才意识到危险，是导致 SUP 事故的主要原因之一。',
 'safety', 'intermediate'),

-- ── 保养维护（maintenance） ──────────────────────────────────────
('充气桨板使用后的正确存放方式是？',
 'single',
 '["充满气存放，避免变形","完全放气后折叠存放于阴凉处","半充气状态直立存放","必须泡在水里保持湿润"]',
 '1',
 '使用后应放气折叠，存于凉爽干燥处，避免长期暴晒（UV 会加速 PVC 老化）。长时间充气存放会使接缝处持续受压，加速老化。',
 'maintenance', 'beginner'),

('碳纤维硬板日常维护最需要注意的是？',
 'single',
 '["每天用清水冲洗","避免碰撞和刮擦，存放时用板袋保护","定期打蜡","不能在海水中使用"]',
 '1',
 '碳纤维是脆性材料，碰撞可能导致表层分层（脱层）。需用专用板袋防护，运输时尽量避免与硬物碰撞。轻微划痕可用环氧树脂修补。',
 'maintenance', 'intermediate'),

('充气桨板发现轻微漏气，正确的处理方式是？',
 'single',
 '["立即丢弃，充气板无法修复","用配套修补包（PVC补丁+专用胶水）修补","用普通强力胶粘上即可","送回厂家才能修复"]',
 '0',
 '等等，答案是错的——充气板可以用配套修补包修复。具体步骤：先用肥皂水找到漏气点，干燥后涂专用 PVC 胶水，贴上补丁，按压 24 小时固化。',
 'maintenance', 'beginner'),

('判断：充气桨板在高温暴晒环境下会自动泄压，因此可以充满气存放在车内。',
 'truefalse',
 '["正确","错误"]',
 '1',
 '错误！高温会使气体膨胀，如果没有安全泄压阀，气压过高会损坏接缝甚至爆裂。即使有泄压阀，高温暴晒也会加速 PVC 老化变脆。切勿将充气板存放在高温密封车内。',
 'maintenance', 'beginner'),

-- ── 运动历史（history） ──────────────────────────────────────────
('现代 SUP 运动最早发源于哪里？',
 'single',
 '["加利福尼亚冲浪海滩","夏威夷威基基（Waikiki）海滩","澳大利亚黄金海岸","巴西里约热内卢"]',
 '1',
 'SUP 起源于夏威夷。20世纪中期，夏威夷冲浪教练为了更好地观察学员、同时帮助摄影，开始站在冲浪板上使用独木舟桨划行，这就是现代 SUP 的雏形。',
 'history', 'beginner'),

('Connor Baxter 是哪个国家的 SUP 职业运动员？',
 'single',
 '["澳大利亚","法国","美国（夏威夷）","丹麦"]',
 '2',
 'Connor Baxter 来自美国夏威夷，是世界最顶级的 SUP 竞速选手之一，多次赢得 APP World Tour 年度总冠军，是 Starboard 品牌的旗帜性运动员。',
 'history', 'intermediate'),

('ICF 哪一年正式将桨板（SUP）纳入管辖范围？',
 'single',
 '["2008年","2012年","2016年","2020年"]',
 '1',
 '2012年，ICF（国际皮划艇联合会）正式将 Stand Up Paddleboard 纳入其运动项目体系，SUP 竞速从此有了国际权威管理机构，并开始有了统一的竞赛规则和世界锦标赛体系。',
 'history', 'intermediate'),

('中国第一个 SUP 相关的国家级赛事大约在哪个年代兴起？',
 'single',
 '["1990年代","2000年代初","2010年代","2020年后"]',
 '2',
 '中国 SUP 竞技赛事体系大致在 2010 年代中期开始发展，随着水上运动普及，全国桨板锦标赛、冠军赛等赛事相继成立，中国桨板俱乐部联赛（CPL）也在这一时期逐步形成规模。',
 'history', 'beginner'),

('桨板运动中的"Downwind"（下风航行）是指什么？',
 'single',
 '["顺着风和涌浪方向划行，借助自然力量高速推进","逆风划行锻炼体能","在船只下风处划行","在水流下游划行"]',
 '0',
 'Downwind 是高级 SUP 技术，选手在开放水域顺着风向和海浪涌流方向划行，通过踩踏涌浪的爆发力获得比平静水面快得多的速度。这是 SUP 中最令人兴奋的专项之一，夏威夷的 Maliko Run 是最著名的 Downwind 线路。',
 'history', 'advanced');
