CREATE TABLE IF NOT EXISTS sup_coach_certificate_checks (
  check_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  athlete_id BIGINT NULL,
  candidate_athlete_ids JSON NULL,
  athlete_name VARCHAR(100) NOT NULL,
  query_name VARCHAR(100) NOT NULL,
  gender_priority VARCHAR(20) NULL,
  result_count INT NOT NULL DEFAULT 0,
  candidate_rank INT NOT NULL DEFAULT 0,
  query_status ENUM('queued','hit','not_found','ambiguous','blocked','error') NOT NULL DEFAULT 'queued',
  certificate_no VARCHAR(120) NULL,
  certificate_no_masked VARCHAR(120) NULL,
  club_name VARCHAR(200) NULL,
  expiry_date DATE NULL,
  source_title VARCHAR(200) NULL,
  source_url VARCHAR(500) NULL,
  source_excerpt TEXT NULL,
  raw_hash VARCHAR(64) NULL,
  match_status ENUM('pending','confirmed','rejected','linked_elsewhere') NOT NULL DEFAULT 'pending',
  professional_id INT NULL,
  checked_at DATETIME NULL,
  next_check_after DATETIME NULL,
  error_message VARCHAR(500) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_coach_check_query_name (query_name),
  INDEX idx_coach_check_status (query_status, match_status, checked_at),
  INDEX idx_coach_check_athlete (athlete_id),
  INDEX idx_coach_check_professional (professional_id),
  CONSTRAINT fk_coach_check_athlete FOREIGN KEY (athlete_id) REFERENCES sup_athletes(athlete_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
