USE sport_hacker;

INSERT INTO sup_events (
  name, slug, event_type, location, province, city, venue,
  start_date, end_date, organizer, description, disciplines,
  star_level, score_coefficient, source_scope, result_status, result_source_note,
  result_source_links, status, event_status
) VALUES
(
  '2024中国桨板公开赛（常熟站）',
  'china-sup-open-changshu-2024',
  'race',
  '江苏省苏州市常熟市琴湖溪里花园城滨湖区',
  '江苏省',
  '常熟市',
  '琴湖溪里花园城滨湖区',
  '2024-06-29',
  '2024-06-30',
  '国家体育总局水上运动管理中心、江苏省体育局、常熟市人民政府',
  '国家级中国桨板公开赛常熟站，设置青少年、高校、大师、公开、卡胡纳等组别，项目包括200米短距离、3000米/6000米长距离、4人龙板赛和5人接力赛。',
  JSON_ARRAY('200米竞速赛', '3000米长距离赛', '6000米长距离赛', '4人龙板赛', '5人接力赛'),
  NULL,
  NULL,
  '全国',
  'none',
  '已补录赛事基础信息，仍缺官方完整成绩册。',
  JSON_ARRAY(JSON_OBJECT('title', '2024中国桨板公开赛（常熟站）开赛_国家体育总局', 'url', 'https://www.sport.gov.cn/n20001280/n20067662/n20067613/c27866455/content.html')),
  'published',
  'completed'
),
(
  '2024中国桨板公开赛（普者黑站）',
  'china-sup-open-puzhehei-2024',
  'race',
  '云南省文山州丘北县普者黑景区',
  '云南省',
  '文山壮族苗族自治州',
  '普者黑景区',
  '2024-06-22',
  '2024-06-23',
  '国家体育总局水上运动管理中心',
  '中国桨板公开赛普者黑站，设置公开组、大师组、卡胡纳组、高校组、U18、U15、U12、U9等组别，覆盖个人赛、接力赛和龙板赛。',
  JSON_ARRAY('个人赛', '5×200米接力赛', '200米龙板赛'),
  NULL,
  NULL,
  '全国',
  'partial',
  '媒体报道披露部分组别冠军，缺官方完整成绩册。',
  JSON_ARRAY(JSON_OBJECT('title', '2024中国桨板公开赛（普者黑站）成功举行_中国日报网', 'url', 'https://cn.chinadaily.com.cn/a/202406/23/WS6677a5d5a3107cd55d2681d1.html')),
  'published',
  'completed'
),
(
  '2024年全国桨板青少年锦标赛暨中国桨板公开赛（青神）',
  'national-youth-sup-championship-china-sup-open-qingshen-2024',
  'race',
  '四川省眉山市青神县',
  '四川省',
  '眉山市',
  '青神县',
  '2024-09-15',
  '2024-09-16',
  '国家体育总局水上运动管理中心',
  '全国桨板青少年锦标赛暨中国桨板公开赛青神站，是国家级青少年与公开组桨板竞速赛事。',
  JSON_ARRAY('200米竞速赛', '长距离赛', '龙板赛'),
  NULL,
  NULL,
  '全国',
  'none',
  '已补录赛事基础信息，仍缺官方完整成绩册。',
  JSON_ARRAY(JSON_OBJECT('title', '2024年全国桨板青少年锦标赛暨中国桨板公开赛开赛_人民网', 'url', 'https://sc.people.com.cn/n2/2024/0916/c407319-40979652.html')),
  'published',
  'completed'
),
(
  '2024年全国桨板U系列赛（安庆潜山站）',
  'national-sup-u-series-anqing-qianshan-2024',
  'race',
  '安徽省安庆市潜山市雪湖桨板基地',
  '安徽省',
  '安庆市',
  '潜山市雪湖桨板基地',
  '2024-10-20',
  '2024-10-20',
  '国家体育总局水上运动管理中心',
  '全国桨板U系列赛安庆潜山站，面向青少年组别与公开组，依托雪湖桨板基地开展竞速与龙板项目。',
  JSON_ARRAY('200米竞速赛', '龙板赛', '青少年组竞速'),
  NULL,
  NULL,
  '全国',
  'partial',
  '媒体报道披露部分组别冠军，缺官方完整成绩册。',
  JSON_ARRAY(JSON_OBJECT('title', '2024年全国桨板U系列赛（安庆潜山站）成功举行_TOM资讯', 'url', 'https://news.tom.com/202410/4055945661.html')),
  'published',
  'completed'
),
(
  '2024年全国桨板U系列赛（南昌站）',
  'national-sup-u-series-nanchang-2024',
  'race',
  '江西省南昌市红谷滩区水上运动基地',
  '江西省',
  '南昌市',
  '红谷滩区水上运动基地',
  '2024-10-27',
  '2024-10-27',
  '国家体育总局水上运动管理中心',
  '全国桨板U系列赛南昌站，设置U18、U15、U12组别，包含200米竞速赛、2000米和4000米长距离赛。',
  JSON_ARRAY('200米竞速赛', '2000米长距离赛', '4000米长距离赛'),
  NULL,
  NULL,
  '全国',
  'none',
  '已补录赛事基础信息，仍缺官方完整成绩册。',
  JSON_ARRAY(JSON_OBJECT('title', '2024年全国桨板U系列赛（南昌站）举行_南昌市人民政府', 'url', 'https://www.nc.gov.cn/ncszf/whtya/202410/b6c21a124a644ad084a11c82df5aae7b.shtml')),
  'published',
  'completed'
),
(
  '2024年中国桨板俱乐部联赛（海口站）',
  'china-sup-club-league-haikou-2024',
  'race',
  '海南省海口市秀英区荣山寮',
  '海南省',
  '海口市',
  '荣山寮',
  '2024-11-22',
  '2024-11-24',
  '国家体育总局水上运动管理中心、海南省旅游和文化广电体育厅',
  '中国桨板俱乐部联赛海口站，设置公开组、大师组、卡胡纳组、高校组和青少年组，项目包括个人200米竞速、6000米/3000米长距离和200米龙板赛。',
  JSON_ARRAY('200米竞速赛', '6000米长距离赛', '3000米长距离赛', '200米龙板赛'),
  NULL,
  NULL,
  '全国',
  'none',
  '已补录赛事基础信息，仍缺官方完整成绩册。',
  JSON_ARRAY(JSON_OBJECT('title', '2024年中国桨板俱乐部联赛（海口站）开赛_国家体育总局', 'url', 'https://www.sport.gov.cn/n14471/n14492/n14529/c28290281/content.html')),
  'published',
  'completed'
),
(
  '2025年中国桨板超级联赛（三门峡站）',
  'china-sup-super-league-sanmenxia-2025',
  'race',
  '河南省三门峡市天鹅湖国家城市湿地公园陕州区水上运动中心',
  '河南省',
  '三门峡市',
  '天鹅湖国家城市湿地公园陕州区水上运动中心',
  '2025-05-17',
  '2025-05-18',
  '国家体育总局水上运动管理中心、三门峡市人民政府',
  '“逐浪黄河风”2025年中国桨板超级联赛（三门峡站）暨第三届“陕州·黄河杯”桨板挑战赛，设置公开组、大师组、卡胡纳组、高校组、青少年组等组别。',
  JSON_ARRAY('男子个人赛', '女子个人赛', '四人龙板赛', '家庭三人龙板赛', '男女混合双人龙板赛', '1000米技术赛'),
  '五星',
  5.0,
  '全国',
  'none',
  '官方报道确认该赛事为2025年度首场五星桨板赛事，仍缺官方完整成绩册。',
  JSON_ARRAY(JSON_OBJECT('title', '2025年中国桨板超级联赛河南三门峡站周末开赛_国家体育总局', 'url', 'https://www.sport.gov.cn/n14471/n14487/n14524/c28707854/content.html')),
  'published',
  'completed'
),
(
  '2025年中国桨板俱乐部联赛（青岛站）',
  'china-sup-club-league-qingdao-2025',
  'race',
  '山东省青岛市奥帆中心水域',
  '山东省',
  '青岛市',
  '青岛奥帆中心',
  '2025-09-15',
  '2025-09-15',
  '国家体育总局水上运动管理中心',
  '中国桨板俱乐部联赛青岛站，在青岛奥帆中心水域开赛，是全国桨板俱乐部高水平交流赛事。',
  JSON_ARRAY('200米竞速赛', '6000米长距离赛', '龙板赛'),
  NULL,
  NULL,
  '全国',
  'none',
  '已补录赛事基础信息，仍缺官方完整成绩册。',
  JSON_ARRAY(JSON_OBJECT('title', '2025年中国桨板俱乐部联赛（青岛站）开赛_青岛政务网', 'url', 'https://www.qingdao.gov.cn/zwgk/xxgk/tyj/ywfl/tycy/202509/t20250916_10227168.shtml')),
  'published',
  'completed'
),
(
  '2025年中国桨板俱乐部联赛总决赛（深圳深汕站）',
  'china-sup-club-league-finals-shenzhen-shenshan-2025',
  'race',
  '广东省深圳市深汕特别合作区南方澳度假村',
  '广东省',
  '深圳市',
  '深汕特别合作区南方澳度假村',
  '2025-12-20',
  '2025-12-21',
  '国家体育总局水上运动管理中心',
  '中国体育彩票·2025年中国桨板俱乐部联赛总决赛（深圳深汕站），设置长距离、200米竞速、四人龙板赛等核心项目。',
  JSON_ARRAY('6000米长距离赛', '200米竞速赛', '四人龙板赛'),
  NULL,
  NULL,
  '全国',
  'partial',
  '媒体报道披露部分项目获胜俱乐部，缺官方完整成绩册。',
  JSON_ARRAY(JSON_OBJECT('title', '2025年中国桨板俱乐部联赛总决赛（深圳深汕站）圆满收官_深圳新闻网', 'url', 'https://www.sznews.com/news/content/mb/2025-12/23/content_31825245.htm')),
  'published',
  'completed'
),
(
  '2026“楚天桨王”系列赛暨湖北省桨板公开赛',
  'chutian-paddle-king-hubei-sup-open-2026',
  'race',
  '湖北省多站点（兴山、嘉鱼、江夏、仙桃、点军、广水、石首）',
  '湖北省',
  NULL,
  '湖北省多站点',
  '2026-05-16',
  '2026-10-18',
  '湖北省体育局水上运动管理中心',
  '2026“楚天桨王”系列赛暨湖北省桨板公开赛，采用6站分站赛+1站总决赛赛制，覆盖青少年组、公开组、大师组，项目包括200米直道竞速、6公里/2公里长距离赛和龙板亲子赛。',
  JSON_ARRAY('200米直道竞速', '6公里长距离赛', '2公里长距离赛', '龙板亲子赛'),
  NULL,
  NULL,
  '本省市',
  'none',
  '省级系列赛，当前只补录公开赛程框架；后续分站成绩册需继续征集。',
  JSON_ARRAY(JSON_OBJECT('title', '2026“楚天桨王”桨板开赛 邀你乘风破浪、水上狂飙_国家体育总局', 'url', 'https://www.sport.gov.cn/n14471/n14488/n14525/c29544151/content.html')),
  'published',
  'ongoing'
)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  event_type = VALUES(event_type),
  location = VALUES(location),
  province = VALUES(province),
  city = VALUES(city),
  venue = VALUES(venue),
  start_date = VALUES(start_date),
  end_date = VALUES(end_date),
  organizer = VALUES(organizer),
  description = VALUES(description),
  disciplines = VALUES(disciplines),
  star_level = VALUES(star_level),
  score_coefficient = VALUES(score_coefficient),
  source_scope = VALUES(source_scope),
  result_status = IF(sup_events.result_status = 'extended_complete', sup_events.result_status, VALUES(result_status)),
  result_source_note = VALUES(result_source_note),
  result_source_links = VALUES(result_source_links),
  status = 'published',
  event_status = VALUES(event_status),
  updated_at = CURRENT_TIMESTAMP;
